### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by ArsenOOO7** [ArsenOOO7/timetable-microservice#102]
Remove all configurations from config-service, there is another special repository for this
Remove all config-files with *-[prod, dev], refactor it using ```---``` operator to separate profiles

Do not forget to edit ```application.yml``` in config-service, ```native``` profile (change path there, use ```search_locations```)

```
spring:
 profile: dev
 datasource:
  ...
 
---

spring:
 profile: prod
 datasource: ...
 ```
